version: '3.3'

services:

  first-game-app:
    command: npm start
#    command: sh -c 'sleep 10000'
    build:
      context: .
    volumes:
      - '.:/app'
    ports:
      - 80:80
#    environment:
#      - NODE_ENV=production
