version: '3.3'

services:

  first-game-app-server:
    command: npm start
#    command: sh -c 'sleep 10000'
    build:
      context: .
    volumes:
      - '.:/app'
    ports:
      - 80:80

  first-game-app-webpack:
    command: npm run watch
    build:
      context: .
    volumes:
      - '.:/app'
    environment:
      - NODE_ENV=production

  cordova:
    command: sleep 100000000
    build:
      context: .
      dockerfile: Dockerfile-cordova
    volumes:
      - '.:/app'