version: '3.5'

services:

  first-game-server:
    image: nginx:1.15.6-alpine
    volumes:
      - ./app/html:/usr/share/nginx/html:ro
    ports:
      - 80:80

#  first-game-app:
#    #    command: bash -c 'sleep 10000'
#    build:
#      context: .
#    volumes:
#      - './app:/app'
#    ports:
#      - 80:80
#    environment:
#      - NODE_ENV=production
